[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "FiraMono Nerd Font Mono", style = "Regular" }
bold = { family = "FiraMono Nerd Font Mono", style = "Bold" }
italic = { family = "FiraMono Nerd Font Mono", style = "Italic" }

[window]
option_as_alt = "Both"
